# Device
DEVICE_ID = ''

# Wifi
DEFAULT_WIFI_SSID = ''
DEFAULT_WIFI_PASSWORD = ''

CONFIG_WIFI_SSID = 'micropython-config'
CONFIG_WIFI_PASSWORD = 'micropythoN'

# MQTT
MQTT_BROKER = '192.168.0.32'
MQTT_PORT = 1883
MQTT_USERNAME = ''
MQTT_PASSWORD = '' 
